name: Deploy generated pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  RepoGeneration:
    name: Repository Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn install

      - run: yarn build

      - run: node dist/index.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
          CLEAN: true
          SINGLE_COMMIT: true
