name: Deploy generated pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
  RepoGeneration:
    name: Repository Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 'Composer install'
        uses: docker://composer:1.10
        with:
          args: install
      - name: 'Generate pages'
        uses: docker://php:7.4-cli
        with:
          args: "php index.php"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: repository

